# Generated by Django 3.2 on 2023-04-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230403_2058'),
        ('reviews', '0006_auto_20230403_2144'),
    ]

    operations = [
    ]
