# Generated by Django 3.2 on 2023-04-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_comment_options'),
        ('reviews', '0007_merge_0006_auto_20230403_2058_0006_auto_20230403_2144'),
    ]

    operations = [
    ]
