# Generated by Django 3.2 on 2023-04-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_merge_20230404_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='code', max_length=6, verbose_name='код подтверждения'),
        ),
    ]
